name = "An pack"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d995498dfab179f02939b7c19370ee88ad3ee780fcdd311a4860250ef1c01bb"

[versions]
forge = "47.4.0"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1-beta1"
