name: Create MMC Export
description: Creates a prismlauncher pack
inputs:
  outputFile:
    description: Output file to generate
    required: true
runs:
  using: composite
  steps:
    - name: Install system dependancies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: zip
        version: 1.0
    - name: Install yq
      uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: 4.45.1
        yq-url: https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64
    - name: Run script
      run: |
        chmod +x ./.github/actions/generate-prism-pack/generatePrismPack.bash
        ./.github/actions/generate-prism-pack/generatePrismPack.bash ./.github/actions/generate-prism-pack ${{ inputs.outputFile }}
      shell: bash