name: Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install packwiz
      uses: ./.github/actions/install-packwiz
    - name: Export for curseforge
      run: packwiz curseforge export --output curseforge.zip
    - name: Create a prismlauncher instance
      uses: ./.github/actions/generate-prism-pack
      with:
        outputFile: prismlauncher.zip
    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Bundles
        path: |
          curseforge.zip
          prismlauncher.zip
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          curseforge.zip
          prismlauncher.zip
        make_latest: true